### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S doc -L siz`

### CODE REVIEW

**Comment by ir33k** [comment]
Wow @kianmeng how in the world did you found this and decided to read the source code?
Anyway, thanks a lot.
I make a lot of typos.

**But to merge this you would have to exclude changes made in `test/walter.h`.**
Typos from this file should be addressed in https://github.com/ir33k/walter/
If you want to open PR there to contribute then go ahead, if not then I will apply those changes there anyway.

BTW Project Yupa is a WIP.
Right at this moment I'm working on Gemini support.

**Comment by kianmeng** [comment]
@ir33k Done. Interested in the Gemini output.

**Review by ir33k — APPROVED** [review]
Gemini support is not there yet but will be done this week.
Thanks for PR

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
